baseurl = "/"
languageCode = "en-us"
title = "Assorted things"
theme = "hugo-lithium"
googleAnalytics = "UA-127831356-1"
disqusShortname = "rafaelmenmell-netlify-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rafaelmenmell"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rafaelmenmell"
[[menu.main]]
    name = "R-Bloggers"
    url = "https://www.r-bloggers.com/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "pigasus.png"
    width = 50
    height = 50
    alt = "Logo"

